# Generated by Django 4.0.3 on 2022-06-15 09:30

import dashboard.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_receivedcargochina_cbm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivedCargoYiwu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('goods', models.CharField(max_length=200, null=True)),
                ('cbm', models.IntegerField(null=True)),
                ('ctns', models.IntegerField(null=True)),
                ('weight', models.IntegerField(null=True)),
                ('remark', models.TextField(null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.client')),
                ('sales_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.salesagent')),
            ],
        ),
        migrations.CreateModel(
            name='DispatchCargoYiwu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('receipt_no', models.CharField(blank=True, default=dashboard.utils.receipt_no, editable=False, max_length=6, null=True, unique=True)),
                ('cbm', models.CharField(max_length=200, null=True)),
                ('ctns', models.CharField(max_length=200, null=True)),
                ('weight', models.CharField(max_length=200, null=True)),
                ('shipping_mark', models.CharField(blank=True, default=dashboard.utils.shipping_mark, editable=False, max_length=6, null=True, unique=True)),
                ('container_number', models.CharField(max_length=50, verbose_name='Cont-N0:')),
                ('remark', models.TextField(null=True, verbose_name='Remarks')),
                ('client_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatchyiwu_name', to='dashboard.client')),
                ('goods', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.receivedcargoyiwu')),
            ],
        ),
    ]
