# Generated by Django 4.0.3 on 2022-07-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offloadedcargo',
            old_name='is_active',
            new_name='is_cleared',
        ),
        migrations.RenameField(
            model_name='offloadedcargo',
            old_name='remark',
            new_name='remarks',
        ),
        migrations.RemoveField(
            model_name='offloadedcargo',
            name='amount',
        ),
        migrations.AddField(
            model_name='offloadedcargo',
            name='paid_amount',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='offloadedcargo',
            name='total_amount',
            field=models.FloatField(null=True),
        ),
    ]
