# Generated by Django 4.0.3 on 2022-07-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_house', '0004_alter_offloadedcargo_paid_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offloadedcargo',
            name='cbm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offloadedcargo',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
