# Generated by Django 4.0.3 on 2022-07-18 13:51

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_receivedcargoyiwu_dispatchcargoyiwu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesagent',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
