# Generated by Django 4.0.3 on 2022-07-19 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dispatchcargochina_goods_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchcargochina',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatched_name', to='dashboard.client'),
        ),
    ]
