# Generated by Django 4.0.3 on 2022-07-19 07:19

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_dispatchcargochina_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, unique=True),
        ),
    ]
