# Generated by Django 4.0.3 on 2022-07-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_client_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchcargochina',
            name='cbm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargochina',
            name='ctns',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargochina',
            name='goods',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargochina',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='dispatchcargochina',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
