# Generated by Django 4.0.3 on 2022-07-19 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_dispatchcargochina_cbm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='cbm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='client_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatchedyiwu_name', to='dashboard.client'),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='ctns',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='goods',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='receipt_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='remark',
            field=models.TextField(blank=True, null=True, verbose_name='Remarks'),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='shipping_mark',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='dispatchcargoyiwu',
            name='weight',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
