# Generated by Django 4.0.3 on 2022-12-31 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_alter_dispatchcargoyiwu_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedcargochina',
            name='client_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
