# Generated by Django 4.0.3 on 2022-12-31 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_alter_receivedcargokenya_goods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receivedcargokenya',
            name='client_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='receivedcargokenya',
            name='goods',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
