# Generated by Django 4.0.3 on 2022-12-31 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_alter_receivedcargokenya_client_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatchcargokenya',
            name='delivery_number',
        ),
        migrations.AddField(
            model_name='dispatchcargokenya',
            name='delivery_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
