# Generated by Django 4.0.3 on 2022-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_house', '0002_rename_is_active_offloadedcargo_is_cleared_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offloadedcargo',
            name='cbm',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='offloadedcargo',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
