# Generated by Django 4.0.3 on 2022-07-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('in_house', '0003_alter_offloadedcargo_cbm_alter_offloadedcargo_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offloadedcargo',
            name='paid_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offloadedcargo',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
